### ISSUE TITLE
Field names translation missing + field name clarification

### ISSUE THREAD

**Issue by mmercapi** [catima/catima#1]
When a new field has been added in an item type, types are not displayed according to the chosen interface language. 

Moreoever, it might be interesting to clarify the field "champ géographique", and especially it's english equivalent "Geometry" as it might not seem very clear that it refers to a JSON input field.

![image](https://user-images.githubusercontent.com/26297183/30593831-3d5c04da-9d4c-11e7-9db4-8e06466c5d63.png)

**Comment by lucaguindani** [comment]
Working on it
[fix-catalog-admin-translation](/catima/catima/compare/development...lucaguindani:fix-catalog-admin-translation)
