### ISSUE TITLE
[Suggestion] Adding navigations buttons "previous" and "next" in item views

### ISSUE THREAD

**Issue by mmercapi** [catima/catima#126]
# Current situation
Currently, navigating through various items requires _going back_ to the item list

# Suggestion
Adding navigation buttons in order to access the previous and next items (according to the item list order) would ease the access to ordered item lists.

# UI Suggestion
![screenshot 2019-02-21 at 10 38 28](https://user-images.githubusercontent.com/26297183/53158950-18a7f280-35c5-11e9-9804-2a432df90f5e.png)

**Comment by lucaguindani** [comment]
solved by #124 (to be merged)
