### ISSUE TITLE
[Bug] Advanced search "date" field has non-pertinent "delete" button in "between dates" mode

### ISSUE THREAD

**Issue by mmercapi** [catima/catima#133]
**Current state**
In an advanced search, selecting "between dates" mode "shows a non-pertinent "delete" button. 

**Screenshot**
![image](https://user-images.githubusercontent.com/26297183/55066474-2b0ec380-507e-11e9-88d2-01f0e63cf806.png)

**Suggestion**
Remove the "delete" button for both dates input in "between dates" mode

**Comment by lucaguindani** [comment]
Not relevant :)
