### ISSUE TITLE
Thumb images not displayed 

### ISSUE THREAD

**Issue by mmercapi** [catima/catima#154]
In setup mode, disabling "edition mode" ("Include this field in edition list view") for image fields prevents "thumb" images displays in "item lists" and search results" thumb" mode.

"Edition mode" enabled for image field
![image](https://user-images.githubusercontent.com/26297183/57379978-4524e100-71a8-11e9-8b55-251834f9b297.png) ==>

![image](https://user-images.githubusercontent.com/26297183/57380003-50780c80-71a8-11e9-8e6b-cf7892f85f4c.png)

"Edition mode" disabled for image field
![image](https://user-images.githubusercontent.com/26297183/57379868-068f2680-71a8-11e9-85d0-d660ab4ecf2c.png)

Test URL :  https://catima.unil.ch/catmanual2/fr/univ

**Comment by lucaguindani** [comment]
Resolved by #231
