### ISSUE TITLE
HTML editor : improve "add video" when adding HVA links

### ISSUE THREAD

**Issue by mmercapi** [catima/catima#227]
### Current situation
Currently, using the "add a video" button of catima html editor (page edition) with an HVA* link does not work. 

Example generated code (not working): 
`<p><video controls="" src="http://av.unil.ch/hva/1742/e-portfolio-720p_hd.mp4" class="note-video-clip" width="640" height="360"></video></p>`

Result is :  "No video with supported format and MIME type found" error" 

![image](https://user-images.githubusercontent.com/26297183/60961704-0aa50500-a30d-11e9-9c90-12a725b06d4b.png)
*UNIL's video plateform "Html Video Automator"

### Enhancement
HVA video integration works with a slight adaptation of generated code, by removing the `http:` part of the source URL.

Example working code : 

`<p><video controls="" src="//av.unil.ch/hva/1742/e-portfolio-720p_hd.mp4" class="note-video-clip" width="640" height="360"></video></p>` 

Result is : working video player
![image](https://user-images.githubusercontent.com/26297183/60962091-cc5c1580-a30d-11e9-8bbf-695dafba7756.png)

**Comment by lucaguindani** [comment]
An embed field is now available to do this kind of integration.
