### ISSUE TITLE
Navigation arrows do not always display correctly

### ISSUE THREAD

**Issue by adnilem** [catima/catima#247]
### Issue
The navigation arrows on the top right of an item do not always display correctly when the item is accessed from a list. It seems to randomly show 0, 1 or both navigation arrows. 

![image](https://user-images.githubusercontent.com/43856420/64525024-2ffbc280-d300-11e9-8dce-e9a344cf9927.png)
Here, _CASES - Cas: Sciences, Ethique et Société_ is not the last item of it's type. It is expected to be able to go to the item before and the one after but it is not possible.

- This behaviour doesn't happen when navigating through the items with the arrows.  _CASES - Cas: Sciences, Ethique et Société_ will have both navigation arrows when accessed from the item before (or after). 
- I couldn't find any pattern about why an item would display 0, 1 or both arrows but it seems that a specific item is always going to display the same number of arrows.

**Comment by lucaguindani** [comment]
Issue fixed
