### ISSUE TITLE
Style inconsistencies

### ISSUE THREAD

**Issue by lucaguindani** [catima/catima#300]
Style inconsistencies due to the bootstrap update.

- Menu
- Data edition mode
- Bookmarks

We'll update this issue if we find more style inconsistencies.

<img width="2296" alt="menu" src="https://user-images.githubusercontent.com/1675064/103775737-c80dd700-502e-11eb-9cb7-41fc9aa9f7d0.png">
<img width="2763" alt="data_overflow" src="https://user-images.githubusercontent.com/1675064/103775748-ca703100-502e-11eb-90d6-f5ccb8b1d55b.png">
<img width="2395" alt="fav" src="https://user-images.githubusercontent.com/1675064/103775755-ce03b800-502e-11eb-8225-d9ba3a346e64.png">

**Comment by skyporter** [comment]
1. menu: we'll update the responsive sizes to match bs3 breakdowns
2. responsive table: "thumbnail" class which has been removed on bs4
3. bookmarks: same of issue 2

**Comment by skyporter** [comment]
also I notice another bug:
4. thumbnail on "gallery mode" (same of issue 2.)

![Capture d’écran 2021-01-06 à 16 11 05](https://user-images.githubusercontent.com/417818/103786662-f7c3db80-503c-11eb-8ee9-47e7b892598e.png)
gallery mode"

**Comment by skyporter** [comment]
5. submenu should not underscore subitem

![Capture d’écran 2021-01-06 à 16 38 20](https://user-images.githubusercontent.com/417818/103787243-a1a36800-503d-11eb-9eab-f414922e2aad.png)

**Comment by lucaguindani** [comment]
Everything is fixed with #301, except the menu issue. I have the same behavior, nothing changed for me.

**Comment by skyporter** [comment]
However, the containers are the same width... 
Other factors influence this positioning, such as the spacing between menu item, the size of the font, even the name of the logged user.

![Capture d’écran 2021-01-07 à 15 37 37](https://user-images.githubusercontent.com/417818/103905458-ecd17f80-50fe-11eb-8db3-05232c2c1cc0.png)
![Capture d’écran 2021-01-07 à 15 38 12](https://user-images.githubusercontent.com/417818/103905286-b72c9680-50fe-11eb-9db5-d5d88c761fe1.png)

**Comment by lucaguindani** [comment]
#302 solve the last issue

**Comment by lucaguindani** [comment]
Style issue when creating a new choice from a record.

![choice](https://user-images.githubusercontent.com/1675064/104735943-883ba380-5742-11eb-9248-916a4a921cb6.png)

**Comment by skyporter** [comment]
notice that issues on label are caused by bootstrap_from gem upgrade which change behavior of rendering `form_group` when `label` contain an empty hash. 
On new version of this gem `form.form_group(method, label: {})` will hide the label and  `form.form_group(method, label: {text: nil})` will display the label (translation with human_attribute_name).

**Comment by lucaguindani** [comment]
Solved by #307
