### ISSUE TITLE
Ahoy track_event

### ISSUE THREAD

**Issue by lucaguindani** [catima/catima#304]
I get a lot of `Unknown primary key for table ahoy_visits in model Ahoy::Visit` errors when I browse through a catalog. I don't have this issue in production. Stacktrace is attached.

[bugsnag_error_stacktrace_ActiveRecord__UnknownPrimaryKey_event_5ffc1098006595f29c310000.txt](https://github.com/catima/catima/files/5794669/bugsnag_error_stacktrace_ActiveRecord__UnknownPrimaryKey_event_5ffc1098006595f29c310000.txt)

**Comment by abstracts33d** [comment]
On local db :
`Ahoy::Visit.primary_key` 
return : 
`=> "id" `

can you please verify staging db.

**Comment by lucaguindani** [comment]
Indeed I imported the database again and the error doesn't come up anymore.
