### ISSUE TITLE
Two "x" icons to exit search in data mode

### ISSUE THREAD

**Issue by adnilem** [catima/catima#305]
In data mode when doing a simple search with the "Search in _Item type_", two x icons appear to close the search. 
The left one only deletes the keyword from the search box while the right one resets the search. 

<img width="502" alt="Screenshot 2021-01-15 at 10 16 43" src="https://user-images.githubusercontent.com/43856420/104705946-cc1ab280-571a-11eb-91d9-239c6da56538.png">

**Comment by lucaguindani** [comment]
Solved by #309
