### ISSUE TITLE
Reference field single value display 

### ISSUE THREAD

**Issue by adnilem** [catima/catima#306]
The reference field's view is very narrow in data mode when adding or editing items. 
This only happens when the reference field's **Data entry options** is set on _Single value - optional_ or _Single value - required_.

It still works to select a reference. 

<img width="838" alt="Screenshot 2021-01-15 at 10 56 10" src="https://user-images.githubusercontent.com/43856420/104711042-23238600-5721-11eb-8ab5-8e3f77d5c3fa.png">

**Comment by lucaguindani** [comment]
Solved by #308
