### ISSUE TITLE
Integer field auto increment

### ISSUE THREAD

**Issue by lucaguindani** [catima/catima#311]
Integer field auto increment is not working. For instance in the "Universités et bibliothèques" catalog if you try to create a new University in the "Universities" item type, the last field (integer) should be auto completed (it's an option of the integer fields).

<img width="600" alt="integer_field" src="https://user-images.githubusercontent.com/1675064/105152547-a3722e80-5b07-11eb-9d54-94d8b48d8b3f.png">

**Comment by abstracts33d** [comment]
same problem with default values

**Comment by lucaguindani** [comment]
Solved by #313
