### ISSUE TITLE
Reference field editor: value field too narrow

### ISSUE THREAD

**Issue by christiankaiser** [catima/catima#312]
When editing an item with a reference field, the value field of the reference field editor is very narrow, and the dropdown is not much wider. Selecting values becomes difficult.

![reference-field-editor](https://user-images.githubusercontent.com/478807/105169127-5dbf6100-5b1b-11eb-94a7-8e5bea3bcc64.png)

**Comment by lucaguindani** [comment]
Cannot reproduce, are you sure you pulled the latest commits from the dev branche ? Looks identical to the resolved issue #306.

<img width="893" alt="CleanShot 2021-01-20 at 13 47 09@2x" src="https://user-images.githubusercontent.com/1675064/105187281-e5649a00-5b32-11eb-8f17-39ddb1b6b5ab.png">

**Comment by christiankaiser** [comment]
Issue seems to be indeed resolved. Thanks.
