### ISSUE TITLE
Translations missing in "New choice set" form 

### ISSUE THREAD

**Issue by mmercapi** [catima/catima#32]
Following text miss translation in French :
- "Name" label 
- "Create and add other" button 

![image](https://user-images.githubusercontent.com/26297183/38084624-ea836af8-334d-11e8-850c-550328373064.png)

**Comment by lucaguindani** [comment]
Working on it
[fix-catalog-admin-translation](/catima/catima/compare/development...lucaguindani:fix-catalog-admin-translation)
