### ISSUE TITLE
Category linked to a choice

### ISSUE THREAD

**Issue by lucaguindani** [catima/catima#321]
When editing an item, a category will be shown multiple times if the item has multiple choice set fields.

![category](https://user-images.githubusercontent.com/1675064/112485848-a1cd1d00-8d7b-11eb-8c9d-1ae84ca01502.gif)

**Comment by lucaguindani** [comment]
Can you please make a quotation for this.

**Comment by skyporter** [comment]
> Can you please make a quotation for this.
