### ISSUE TITLE
Translations missing in "New choice set field" form

### ISSUE THREAD

**Issue by mmercapi** [catima/catima#33]
Following translations are missing : 

- "Name" label

- Slug's indications : "Lower case letters, numbers, and hyphens only. No accented characters."

![image](https://user-images.githubusercontent.com/26297183/38240020-a4ec07a4-372e-11e8-848a-2ed44e9e1a75.png)

**Comment by lucaguindani** [comment]
Working on it
[fix-catalog-admin-translation](/catima/catima/compare/development...lucaguindani:fix-catalog-admin-translation)
