### ISSUE TITLE
"Edit category" button not fully translated

### ISSUE THREAD

**Issue by mmercapi** [catima/catima#34]
When selecting a specific category, the edition button is not fully translated (here some mix of French and English "Editer category"

![image](https://user-images.githubusercontent.com/26297183/38250628-8f506f5e-374f-11e8-8fd6-f963c5bade1f.png)

**Comment by lucaguindani** [comment]
Working on it
[fix-catalog-admin-translation](/catima/catima/compare/development...lucaguindani:fix-catalog-admin-translation)
