### ISSUE TITLE
Half translated field

### ISSUE THREAD

**Issue by melindafemminis** [catima/catima#347]
In `Catalog set up > Users & groups` the *Last signed in* field is only half translated when using a different language than english. The date is correctly translated but **ago** is still in english.
This behaviour happens in catalogs that use french as the main and only language as well as in multilingual catalogs.

<img width="224" alt="c-english-ago" src="https://user-images.githubusercontent.com/43856420/121269553-a9359a00-c885-11eb-9d17-265917fc228b.png">

*Selected language: english*

<img width="220" alt="f-english-ago" src="https://user-images.githubusercontent.com/43856420/121269621-c9fdef80-c885-11eb-8098-64aeed74b899.png">

*Selected language: french*

**Comment by lucaguindani** [comment]
Solved by 5ea5cc837a0b09c0da6a97c6ec10105d70de2fa9
