### ISSUE TITLE
HTML container: changes no saved when editing in Code view

### ISSUE THREAD

**Issue by melindafemminis** [catima/catima#349]
### Issue
After editing a page's HTML container in Code view, the changes are not saved when clicking on the **Save changes** button. The success message `The “name_of_container” container has been saved.` is displayed and the changes are lost.

### What works
To save changes made from Code view, switch back to normal text editing then click on **Save changes**.

**Comment by lucaguindani** [comment]
Solved by d80f269fbe0d5a8cc7800aa46aefd6eea15b0fd3
