### ISSUE TITLE
Item's status not updated in data list view

### ISSUE THREAD

**Issue by melindafemminis** [catima/catima#351]
Edit an item that has the *Review* status to approve or reject if. Click on either button in the yellow box in the edit page, then click on the *Back* button. This will save the changes; an *Approved* item will be published and a *Rejected* item will not. The problem is that the status in the status column is not updated and still shows *Review*. When editing the same item again, it will show the correct tag: *Approved* or *Rejected*. 

The status column will show the correct tag once the page is reloaded or by editing and saving the item by clicking on the *Save "Item name"* at the bottom of the page.

This does not happen when clicking on the *Save "item name"* button instead of the back button after choosing to approve or reject and item.

**Comment by lucaguindani** [comment]
Solved by 23a9ec713755838a608547dcf127da705094d95d
