### ISSUE TITLE
GeoViewer in item show

### ISSUE THREAD

**Issue by lucaguindani** [catima/catima#384]
Geographic field not working in item show view. No console error.

![CleanShot 2021-11-02 at 15 21 53](https://user-images.githubusercontent.com/1675064/139866573-8052d90b-b11b-489d-8eb3-d0d3d681ed78.png)

**Comment by abstracts33d** [comment]
![image](https://user-images.githubusercontent.com/16547134/140044345-068faa72-eadb-4a8a-bad6-4e2626f99580.png)
