### ISSUE TITLE
Placeholder in advanced search

### ISSUE THREAD

**Issue by lucaguindani** [catima/catima#386]
We have a strange placeholder when using an advanced search by reference. Select a field, then clear it -> the "By Item..." placeholder is replaced by "all_words".

![CleanShot 2021-11-03 at 09 49 52](https://user-images.githubusercontent.com/1675064/140037582-f9e7e985-3ea1-46d1-b4e9-586cf7da3148.gif)

**Comment by abstracts33d** [comment]
![image](https://user-images.githubusercontent.com/16547134/140047105-36218e55-dbbc-479b-a42c-2f83976adaf4.png)
![image](https://user-images.githubusercontent.com/16547134/140047139-1df5c91a-ff45-4762-9d82-a494452983b5.png)
