### ISSUE TITLE
Custom advanced search

### ISSUE THREAD

**Issue by lucaguindani** [catima/catima#387]
Custom advanced search with a "Map" display type is not behaving as expected. The component used to display the results on a map is not working when a search is made.

![CleanShot 2021-11-03 at 10 58 04](https://user-images.githubusercontent.com/1675064/140040878-cabcbc01-3f30-419f-8f29-9ddf82d8e37a.gif)

**Comment by abstracts33d** [comment]
Custom advanced search #387
