### ISSUE TITLE
GeoEditor component

### ISSUE THREAD

**Issue by lucaguindani** [catima/catima#388]
Cannot delete a point in the GeoEditor component.

![CleanShot 2021-11-03 at 13 58 14](https://user-images.githubusercontent.com/1675064/140065471-81029d31-f0c0-4b4c-8e2e-46f668e0e820.gif)

**Comment by abstracts33d** [comment]
![image](https://user-images.githubusercontent.com/16547134/140077803-35f27dce-d3be-4e32-9327-c9255c3c8703.png)
