### ISSUE TITLE
Insert button completely white when inserting a link in a page

### ISSUE THREAD

**Issue by melindafemminis** [catima/catima#396]
When adding a link to a HTML container in a page with the edit button in the toolbar, the "**Insert Link**" button is completely white when a link is added. 

Insert Link button is disabled but visible when fields are empty:
<img width="595" alt="no-link" src="https://user-images.githubusercontent.com/43856420/145182928-3205758c-a3e5-4973-8436-89f051d09881.png">

Insert Link button is white when a link is added:
<img width="592" alt="with-link" src="https://user-images.githubusercontent.com/43856420/145183033-ceba29d2-1506-4856-8da5-a1acd236dd47.png">

Insert Link button reappears when hovering over it with the mouse:
<img width="593" alt="with-link-and-hover" src="https://user-images.githubusercontent.com/43856420/145183263-3dbea5d1-267e-48b2-894d-7e2a9763eba4.png">

**Comment by lucaguindani** [comment]
Solved by 248dad133c450581bc92864f323b3d182a2b7e6a
