### ISSUE TITLE
Compound field - API & exports

### ISSUE THREAD

**Issue by lucaguindani** [catima/catima#397]
The data of a "Compound" field is not available in JSON (Catima) & SQL export types.

![comp_json_export](https://user-images.githubusercontent.com/1675064/145815010-a96fa2e9-edfa-45ab-8af7-1e2e57f591dd.png)
![comp_sql_export](https://user-images.githubusercontent.com/1675064/145815025-e5efbf4b-e995-4601-9653-d39921bc159c.png)

The data of a **multilingual** compound field is not available in the API and in the JSON (Catima) and SQL export types.

![comp_multi_api](https://user-images.githubusercontent.com/1675064/145815264-5c89a86d-3272-415d-8636-f4a86cf8d418.png)

The data of a multilingual compound field should be available in the API and in the JSON (Catima) and SQL export types (only current language needed for a CSV export). It should follow the structure of a multilingual text field (screens below).

![CleanShot 2021-12-10 at 17 51 32](https://user-images.githubusercontent.com/1675064/145815826-a680e85e-6134-4f8e-8d1c-a4e2e8a67cc4.png)
![CleanShot 2021-12-10 at 17 20 32](https://user-images.githubusercontent.com/1675064/145815828-59789265-6c67-404e-a9fb-8c32515e58c0.png)
![CleanShot 2021-12-10 at 17 18 06](https://user-images.githubusercontent.com/1675064/145815829-aad1d96e-f1db-47fb-bec5-ae91aeef40c9.png)
ns below).

! The sql_type of a compound field is not the same if the field is multilingual or not (example below -> _JSON_ if multilingual, _TEXT_ if not).

https://github.com/catima/catima/blob/3d28d1be658df7704b33ff7114ea5551bb9bc760/app/models/field/url.rb#L44

**Comment by abstracts33d** [comment]
export => valeurs
api => template / valeurs

**Comment by lucaguindani** [comment]
Solved by 6816473b7ede60d1d4e24bd6792c16e9c683119f
