### ISSUE TITLE
Language selection not taken into account when changing link

### ISSUE THREAD

**Issue by mmercapi** [catima/catima#4]
Selecting a language _via_ the dropdown menu in the "site" section applies language correctly when navigating the site (ie through item types). 

However, only first link of data / setup keeps language parameter (for example `?locale=fr`). Further browsing to other links (ie to other item type) looses this parameter. Adding for example `?locale=fr` to URL fixes _this_ translation problem.

**Comment by mmercapi** [comment]
Hi @lucaguindani ! "Site" meant the rendered website for visitors. As I can not reproduce the forementioned issue, my guess is it might have been solved in the meantime.

**Comment by lucaguindani** [comment]
Ok great ! Thanks
