### ISSUE TITLE
ItemList container - reference sort field

### ISSUE THREAD

**Issue by lucaguindani** [catima/catima#418]
L'utilisation d'un Sort field de type référence (avec comme primary un text single value) ne fonctionne pas (erreur retournée).

![CleanShot 2022-02-23 at 15 04 34](https://user-images.githubusercontent.com/1675064/155337279-77b5a457-f308-4cda-89af-b98a25d71cb1.png)

**Comment by abstracts33d** [comment]
il me faudrait plus d infos sur ce cas car en testant de mon coté cela fonctionne
