### ISSUE TITLE
ItemList container - choiceset as primary field

### ISSUE THREAD

**Issue by lucaguindani** [catima/catima#420]
Quand le primary field de l'item type utilisé pour un ItemList container est un choiceset, une erreur est retournée lors de la visualisation du container.

![CleanShot 2022-02-23 at 16 03 27](https://user-images.githubusercontent.com/1675064/155346856-bd1af60f-1267-494e-b716-2b8d391ec496.png)

**Comment by abstracts33d** [comment]
ok
