### ISSUE TITLE
ItemList container - integer/decimal sort field

### ISSUE THREAD

**Issue by lucaguindani** [catima/catima#423]
L'utilisation d'un Sort field de type integer/decimal ne fonctionne pas. La "Line" n'affiche pas de groupe et certaines parties de l'interface ne sont pas utilisables.

**Comment by abstracts33d** [comment]
tu avais explicitement demandé de ne pas grouper les int / decimal. quelles parties de l interface ne sont pas utilisables ?

**Comment by lucaguindani** [comment]
Non, on avait demandé de ne pas faire de **sous-groupes** (ce qui est logique vu la nature de ce type de champ), mais pas sans groupement.

--------------
- Pour chiffres/nombres (integer, decimal)
    - Faire un affichage sans sous-groupe
--------------

L'interface de select asc/desc ne fonctionne pas dans mes tests. Et il n'y a pas de close/open all.

**Comment by abstracts33d** [comment]
j ai remis le groupe de premier niveau et le open close all en ce qui concerne le select asc/desc c est le comportement actuel qui pose problème ( le tri ne fonctionnais pas avant la story line)
