### ISSUE TITLE
No more image accessible in catalogue "DocTech"

### ISSUE THREAD

**Issue by mmercapi** [catima/catima#5]
Images in catalogue ["DocTech"](https://catima.unil.ch/doctech/fr/notices) have been replaced by their filename (1st image below). Furthermore URLs refering to images returns Catima's 404 error (2nd image below).

![image](https://user-images.githubusercontent.com/26297183/32505200-e2046516-c3e1-11e7-82a6-994e40cf9e73.png)![image](https://user-images.githubusercontent.com/26297183/32505168-cdfcd012-c3e1-11e7-8a17-0e21a49bcbeb.png)

**Comment by lucaguindani** [comment]
Not the case anymore.
