### ISSUE TITLE
Can't remove a menu item with itself as parent

### ISSUE THREAD

**Issue by daviserez** [catima/catima#503]
## Problem
When you create a menu item, and you chose itself as parent, removing this menu item raise an exception.

Perhaps, we should restrict the ability to chose as parent the menu item itself in first place.

## Steps to reproduce
1. Creat  a menu item.
2. Save it and edit it to chose itself as parent.
3. Try to remove this menu item.

**Comment by lucaguindani** [comment]
Solved by 0f2e183
