### ISSUE TITLE
ItemList on page when no item type exists raise an exception

### ISSUE THREAD

**Issue by daviserez** [catima/catima#504]
## Problem
On a new catalog with no item type created, if we create a page and add an item list container, we can't save it.
It's because the field item type is empty. We should see "Can't be blank" on the field instead of the exception.

## Steps to reproduce
1. Create a new catalog (do not add any item type)
2. Create a page.
3. Add a container item liste style.
4. Click on Save container.

**Comment by lucaguindani** [comment]
Solved by 952330a
