### ISSUE TITLE
Import issues

### ISSUE THREAD

**Issue by powerriegel** [catima/catima#520]
Hello,

I've observed two issues when using the import feature of Catima 2.24.2.  One seems to be quite severe, the other is easy to work around. 

# Importing mixes imports with existing datasets
If you have a couple of records with multiple images  stored and then importing, the result is that the imported records are somewhat mixed within the existing datasets. I noticed this by viewing the images of one record. One image was original, the other was imported and overwrote the second original image. 

# Importing from nextcloud crashes the app. 
The app repeatedly crashed when trying to import from a nextcloud share in Android 13. Exporting to such a share in Android 10 was no problem. To work around this, users can save the catima.zip to their Downloads folder and then import works.

**Comment by lucaguindani** [comment]
Hello @powerriegel, your issue was maybe added to the wrong Catima projet ? Seems to me something like https://github.com/CatimaLoyalty/Android would be a better fit for your request.

**Comment by powerriegel** [comment]
Lol, thanks!
