### ISSUE TITLE
Use the same map base layers for editing and viewing geographic fields.

### ISSUE THREAD

**Issue by christiankaiser** [catima/catima#55]
The map base layer is not the same in edition and in the public view.
https://catima.unil.ch/atlastopvaud/fr/admin/toponymes/3497-addos/edit
https://catima.unil.ch/atlastopvaud/fr/toponymes/3497-addos

Is it possible to have the topographic version in both views ?

**Comment by lucaguindani** [comment]
Should be resolved with PR #146
