### ISSUE TITLE
[Item view] "Code view" mode not working

### ISSUE THREAD

**Issue by mmercapi** [catima/catima#56]
When editing an item view, clicking on "code view" button greys out and blocks the editing zone. Thus "code view" functionnality is currently unavailable.

![image](https://user-images.githubusercontent.com/26297183/42580520-0a97a60e-852b-11e8-9530-408f587c891e.png)

**Comment by lucaguindani** [comment]
Issue solved with https://github.com/catima/catima/pull/60
