### ISSUE TITLE
[Translation] New item's button translated incorrectly

### ISSUE THREAD

**Issue by mmercapi** [catima/catima#69]
In a catalog's data section, adding an item in French is translated incorrectly.

Current translation : "Nouveau type de fiche <type de fiche>". 
New translation proposal : "Nouvelle fiche <item type name"" . 

English version
![image](https://user-images.githubusercontent.com/26297183/45746373-6a59e480-bc03-11e8-96dc-99ee528fbd11.png)

French version (incorrect)
![image](https://user-images.githubusercontent.com/26297183/45746387-75ad1000-bc03-11e8-89da-0d78ca734053.png)

**Comment by lucaguindani** [comment]
Solved with #72
