### ISSUE TITLE
[Suggestion] Opening a new catalog redirects to list of users

### ISSUE THREAD

**Issue by mmercapi** [catima/catima#70]
After sys admin has created a new catalog, accessing the catalog for the first time (and until an item type has been created) redirects to the list of users (Menu "Users") which might be a bit confusing.

We suggest redirecting to another page, such as "Settings" (allowing to change catalog's name) or to a generic "Welcome to Catima" page.

**Comment by lucaguindani** [comment]
solved with aa0daade8a93f04a552b04e6532aa061675e2eb5
