### ISSUE TITLE
[Translation] "Edit item type" translation missing in French

### ISSUE THREAD

**Issue by mmercapi** [catima/catima#71]
In the Setup section of a catalog, the "Edit item type" button is not fully translated. 

![image](https://user-images.githubusercontent.com/26297183/45746923-b8231c80-bc04-11e8-85d3-3e4671fc8a11.png)

We suggest following translations : "Editer type de fiche" or "Editer <item type>"

**Comment by lucaguindani** [comment]
Solved with #72
