### ISSUE TITLE
[Data] Sorting an item type by reference field displays items alphabetically unordered 

### ISSUE THREAD

**Issue by mmercapi** [catima/catima#82]
In the Data section, sorting an item by a field other than the primary field (here the reference field  "Université") displays items alphabetically unordered by the forementioned field but also by primary fieldl "Nom de bâtiment".

![image](https://user-images.githubusercontent.com/26297183/46653522-91725900-cba6-11e8-9094-d718f8406f73.png)

**Comment by lucaguindani** [comment]
Fixed with #102
