### ISSUE TITLE
Formatted text not rendered correctly in reference editors

### ISSUE THREAD

**Issue by lucaguindani** [catima/catima#87]
![46796846-ddabcd80-cd4d-11e8-9bb6-9101de7ff139](https://user-images.githubusercontent.com/1675064/47069033-3962d480-d1ee-11e8-9f2c-0db8a7d432ed.png)
![46802922-186a3180-cd5f-11e8-94ec-9e6c6a6498cd](https://user-images.githubusercontent.com/1675064/47069034-3962d480-d1ee-11e8-9421-64010dea858f.png)

**Comment by lucaguindani** [comment]
It's a behavior that can be reproduced with both editors (MultiReferenceEditor, SingleReferenceEditor).

**Comment by jurtn** [comment]
PR #88 fixes this problem.
