### ISSUE TITLE
[Translation] French translations missing in "Item view" editor 

### ISSUE THREAD

**Issue by mmercapi** [catima/catima#90]
When adding/editing an item view, some headings and buttons are not fully translated : 

*"Edit item view" heading
* Template editor
  * Tooltips (mouse hover on buttons)
  * Buttons names ("Add field", "Item link")

![image](https://user-images.githubusercontent.com/26297183/47355080-b693bb00-d6c0-11e8-84b3-768298379f9c.png)

**Comment by lucaguindani** [comment]
Item views are now SysAdmin only, no more translation needed
